server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: scott
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver